### ISSUE TITLE
[FIXED] 2016 update

### ISSUE THREAD

**Issue by sergeevabc** [TLHobbes/OptionLock#1]
Dear Mr. Hobbes, could you be so kind to update OptionLock?
Keepass UI has slightly changed over the past four years since the plugin’s release.

**Comment by TLHobbes** [comment]
Hi sergeevabc, apologies for the delay in response; I have updated OptionLock to version 1.1.0.0 - developed against the latest version of KeePass, which at time of writing is KeePass 2.32.

**Comment by sergeevabc** [comment]
Thank you, @TLHobbes.
